export default {
  '00:02': `Ooh-ooh, yeah, I do`,
  '00:05': `You know I got a crush on you`,
  '00:09': `Ooh-ooh, oh, it's true`,
  '00:12': `You know I got a crush on you`,
  '00:16': `And I try to play it cool`,
  '00:18': `But there's only so much I can do`,
  '00:23': `'Cause ooh-ooh, oh, I do`,
  '00:25': `You know I got a crush on you`,
  '00:29': `You might have an idea`,
  '00:32': `How I feel when I'm with you`,
  '00:36': `But did you know it goes deeper?`,
  '00:39': `'Cause, oh, it goes deeper`,
  '00:43': `Overjoyed when I see you`,
  '00:46': `Baby, but when you're leaving`,
  '00:49': `I lose a piece too`
  // `'Cause it goes with you, but`,
  // `I could think about you`,
  // `Every single hour`,
  // `She got superpowers`,
  // `Ooh-ooh, yeah, I do`,
  // `You know I got a crush on you`,
  // `Ooh-ooh, oh, it's true`,
  // `You know I got a crush on you`,
  // `And I try to play it cool`,
  // `But there's only so much I can do`,
  // `'Cause ooh-ooh, oh, I do`,
  // `You know I got a crush on you`,
  // `You might think it sounds crazy`,
  // `Someone calling you baby`,
  // `It's new for me too`,
  // `But I'd try with you`,
  // `Overjoyed when I see you`,
  // `Baby, but when you're leaving`,
  // `I lose a piece too`,
  // `'Cause it goes with you, but`,
  // `I could think about you`,
  // `Every single hour`,
  // `She got superpowers`,
  // `Ooh-ooh, yeah, I do`,
  // `You know I got a crush on you`,
  // `Ooh-ooh, oh, it's true`,
  // `You know I got a crush on you`,
  // `And I try to play it cool`,
  // `But there's only so much I can do`,
  // `'Cause ooh-ooh, oh, I do`,
  // `You know I got a crush on you`,
  // `C-R-U-S-H`,
  // `Girl, whatcha doing to me?`,
  // `I get crushed under the weight, yeah`,
  // `C-R-U-S-H`,
  // `Girl, whatcha doing to me?`,
  // `I get crushed under the weight`,
  // `'Cause ooh-ooh, yeah, I do`,
  // `You know I got a crush on you`,
  // `Ooh-ooh, oh, it's true`,
  // `You know I got a crush on you`,
  // `And I try to play it cool`,
  // `But there's only so much I can do`,
  // `'Cause ooh-ooh, oh, I do`,
  // `You know I got a crush on you, ooh`,
}
